### ISSUE TITLE
The sleep stage in the txt file conflict with the Hypnogram.edf files

### ISSUE THREAD

**Issue by joycejyin** [anas-imtiaz/sleep-edfx-toolbox#2]
First I just wonder the txt file in the info folder from your team?  
As I can see the code like this:
annotations_url = 'https://workspace.imperial.ac.uk/rodriguez-villegas-lab/Public/edfx-toolbox-files/';

Second I find the sleep stage in SC4011E0.txt file is conflict with the sleep stage in SC4011EH-Hypnogram.edf file
for example  in SC4011E0.txt Line 34
 [00:03:30.000 30/03/1989]  2607000     "    0    0    0	Sleep_stage_1 duration: 90
but in SC4011EH-Hypnogram.edf provided by physionet first line it says
Sleep stage W    00:00:00
Many conflicts like this, can you tell me why

**Comment by anasimtiaz** [comment]
The annotations_url is indeed our workspace where we have hosted some of the processed files to make the processing easier for us. You can always retrieve it from PhysioNet but that will be a longer process.

Second, I am not entirely sure where the confusion is. I have checked the annotation file on PhysioNet too just to confirm and it is exactly the same. The first line in EDF says the sleep stage is Wake at time 0 and that is also confirmed by line 4 in the .txt file. Why are you comparing it with line 34?

**Comment by joycejyin** [comment]
Really happy and appreciate for your prompt reply.
I suddenly realized I have made a mistake for selecting the "Relative" filter when viewing the edf file.
Thank you very much and Sorry for the disturbing.
