### ISSUE TITLE
access to workspace.imperial.ac.uk 

### ISSUE THREAD

**Issue by oscardamb** [anas-imtiaz/sleep-edfx-toolbox#3]
Hi. I've been testing the ToolBox recently, but when I try to download the annotations, it throws a re-established connection error and the process is paused there. Are the annotation files still hosted on the server or is the url no longer functional? if the url is not available, how can I downlod the annotation files?

Thank you for your attention.

**Comment by anasimtiaz** [comment]
Hi. The url is no longer available so I will update this over the weekend. Thanks for pointing it out

**Comment by Lukas1223** [comment]
Hi. I have the same issue. I would appreciate it if you could update the url.
Thank you very much.

**Comment by anasimtiaz** [comment]
Hi, this should be fixed now.
